a = input('Digite algo: ')
print('o tipo primitivo desse valor é: {}'.format(type(a)))
print('Só tem Espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está Maiúscula? {}'.format(a.isupper()))
print('Está minúscula? {}'.format(a.islower()))
print('Está capitalizada {}'.format(a.istitle()))
